name: uc-python
channels:
    - defaults
    - conda-forge
dependencies:
    - python>=3.9
    - pip>=20.3
    - numpy=1.19
    - pandas=1.2
    - seaborn=0.11
    - ipykernel=5.3
    - jinja2=2.11
    - jedi=0.17.2
